# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Z_w_OfSaSC0FW2Lgj38ovyvL-hNszBD
"""

import matplotlib.pyplot as plt
import numpy as np


x=np.array([0,6])
y=np.array([0,250])


plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x=np.array([1,2,6,8,10,12,15,21,28])
y=np.array([3,8,7,9,1,17,11,25,21])


plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,8,7,9,1,17,11,25,21])


plt.plot(y, marker="o")
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,8,7,9,1,17,11,25,21])


plt.plot(y, 'o:r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,8,7,9,1,17,11,25,21])


plt.plot(y,marker='o',ms=20)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,8,7,9,1,17,11,25,21])


plt.plot(y,marker='o',ms=20,mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y=np.array([3,8,7,9,1,17,11,25,21])


plt.plot(y,marker='o',ms=20,mfc ='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x=np.array([0,0,35,35])
y=np.array([0,35,0,35])


plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x=np.array([0,0,35,35])
y=np.array([0,35,0,35])
mycolor=['red','green','purple','lime']

plt.scatter(x,y,color=mycolor)
plt.show()

